# Generated by Django 4.2.2 on 2023-06-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_purchases_day', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_purchases_week', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_purchases_month', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_purchases_year', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.store')),
            ],
        ),
    ]
